apiVersion: account.btp.orchestrate.cloud.sap/v1alpha1
kind: Entitlement
metadata:
  name: myproduct-cis-entitlement
spec:
  providerConfigRef:
    name: myproduct-providerconfig
  forProvider:
    serviceName: cis
    servicePlanName: local
    enable: true
    subaccountRef:
      name: myproduct-subaccount
---
apiVersion: account.btp.orchestrate.cloud.sap/v1alpha1
kind: Entitlement
metadata:
  name: myproduct-cls-entitlement
spec:
  providerConfigRef:
    name: myproduct-providerconfig
  forProvider:
    serviceName: cloud-logging
    servicePlanName: standard
    amount: 2
    subaccountRef:
      name: myproduct-subaccount
---
apiVersion: account.btp.orchestrate.cloud.sap/v1alpha1
kind: Entitlement
metadata:
  name: myproduct-kyma-entitlement
spec:
  providerConfigRef:
    name: myproduct-providerconfig
  forProvider:
    serviceName: kymaruntime
    servicePlanName: azure
    enable: true
    subaccountRef:
      name: myproduct-subaccount