apiVersion: v1
kind: Secret
metadata:
    name: regcred
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:/CQkAnwY4gUo6B2lkcNFqmCGB4TgcWdNidCzXg1wzf2xCaZm8j7AJ51KdqI9fJ7t3MmdshgZw/g7wN0RgHS8E9itZHOqVYCc3sc94k7hPnfuH8WJIjGwwbLbB/Ql4sucD/FjGuKzjDlcBL6QAIczBIdpfIcZA8Ll/suc5ngENPTZDBKf/Q6YnCCi8e97c72frKpPCWoplZ1o1OyKPo0/L+Py6+yYlwi5lonc/hC9MTAGPV9syF0WiyWMWgdWcUgHQSlRCZH9w3Rql4aK+YeTwjHE5Ohi88tq6eOxorrwoo2QcF6U5l5ulB/ptXizdnMZlkghuce6HdP2CTmNls3RYOuJnRQc8tu2ojVooJ4lfxyuNmJpanXpA94jsTA=,iv:aZgSNn0OvYZOMOaULm3EcDu9etzVmVFs4kPNlkZVOeI=,tag:Q+cjdutQi6iXDvueal+ZHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-25T21:01:23Z"
    mac: ENC[AES256_GCM,data:4TZch4d8t8XuYQcRGLI+setXRb7iQg6IehfwZl452IxsrEs5cEVAvpQC0LtXI5dQ3ovk3Q1p/Bq96br2xoCOnzakgaIFpmwXz+k2J5sGMdIDPHLm842OTAiVPM9TXX/BfiIQCTiAJvhqx7jRUSYgxAZCw5+cR7Pniho0mK9gd4w=,iv:ciKeHbzS6SZBWJk+bmRXAwnodsFMjG2nv7tBQZZ4dfM=,tag:BV+fzyBPhhnjyp/n0mbm+g==,type:str]
    pgp:
        - created_at: "2023-03-25T21:01:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+09R1QdBDPoAQ/+KL1ZDhpEZewfwZvPuQs87GxG/73s1NSEk8B1aR9ejYQZ
            0zKwK9AIOhOWqNAn9WuXuhWqPOOaLWAER47QEuIJIQ3ljCE0bvwqe+drav3H2vnD
            OQy6caO4ZSTEqZ3EcgpoD+ZNyebXloX94Vl/e95qFQgtB6EpUgJRT3CL2Mj5+UPs
            iWb4ZfcAkPmJQLBbBusDCt1Ymj1xN51HOoI4LzM9yuF88NSpnCrV1HBXqFWwqQ7H
            epD8NO645fwHgzT9vkA+gQrGNLl6+0XDYVMm+ByS8GFEJFpRRAV3CPLe7hYLAvBq
            g3tOT+Kf/L2nsRNGhl4KTmXwF8fjuI66tDH0e7NdViqvqAJrsSu1UP8QenKmxKU2
            elKywFxa7Cdad+H80zJ0ZFGvkLAQrG1OR/wnZmNb7MY/1PIZp1+/Wxs9BLVTNbtD
            TY/ue2V5prJDRx5WBJym5yPgy8MPqtETkmJuTb9ZW5Vn2wZHZnUEVFkJhfjEv0v3
            eXdOD4dR2O3E5xecbctLly60twmm3SssTXh/584hMDPVNG2wpyZ41Uj1KfhaLVoh
            C6BqqXWAB0dLF7jjEkYVNgn33tmc91YjpnxY4MsYeJj0/L91mlnMdOxtLfqlHFiQ
            ni4avsIWCbPccEulKfiIvtzoGw76YjwXavMQnZn6Wy8lKRqcG9XVMKzjVqj0PmrS
            XgHC2AmhNI8EBhE6FSoSxHCaI8Z9EsGAolMIS/326H/rjf2li+HFQFCY9l43X5za
            6fmwzkC3e/nG/YCNpbZUKgMxix26h0TTt11o2WJoclHP/iNsJD1e0HzByJT4jMQ=
            =yezy
            -----END PGP MESSAGE-----
          fp: F2D69C1B0CC762DD3814C50C58C374DB3C89C7DE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
