apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-co-demo-status
spec:
  providerRef:
    name: flux-co-demo-status
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
