apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 1_namespace.yaml
- 2_gitrepository.yaml
- 3_fluxkustomization.yaml
- 4_provider-github.yaml
- 5_alert-github.yaml
- 6_secrets_github-sops.yaml

namespace: mpas-system