apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-co-demo
  namespace: vasu
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-co-demo
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg