apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-co-demo
  namespace: vasu
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-co-demo
  timeout: 60s
  url: ssh://git@github.com/vasu1124/flux-co-demo
