#P2005905884
# User needs to have Global Account viewer access
apiVersion: v1
kind: Secret
metadata:
    name: sa-provider-secret
    namespace: btp-co-demo
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:Zi3qjWhytrgPM0ZWJ0skQnp8S5RJvzfFvd4bSddtQXhrdzcvqrI+S2ujyfb7qlcXH3KS3Apk224/Ukw39J9ZSCE6W3EkKHrbeNJbhE/qrOF4YQLGTFQSqgNR6+tseSDgB3v5zCKEk+bzmh39JQj/kDmr2VH3H1MLdjVRdcHmn9Xp2vMxVgrFJYbRcxm/xA9vRGDsh5BtxxcvQq1s8tcumB4=,iv:/W8YkY4Yhbir/RYni+804O038WtsSlZvaf+omvtVZ6M=,tag:2fL0S2/8qoGXlRgJv6xWIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-25T19:13:44Z"
    mac: ENC[AES256_GCM,data:oqQt+tRI6dYL5K5ei9FWlnX0FPlsHyEmTDqbteBnzwu3p71KAV+ZZDAqs4HJ3uVcVuliwlq+z3xG/JfNKPZIFMW4qRZA98jxZGNyu1y/5iKFfCsIrLzoW8WBn9Y0YItxufnYbx9DeK3tSyjrrrInIx1SKcEyj9J+uwps8IJSCxE=,iv:by+4SUSaqFcIIljcNokiWYBA3ceIwSe5MGqpLml1f+s=,tag:RtSnRl0JuTbzMbsF/3sZww==,type:str]
    pgp:
        - created_at: "2023-03-25T19:13:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+09R1QdBDPoAQ/9GXrccmbQdcpTjp9s9oycodg2yE1Ok+JpHYhUUZAf2w1h
            kBXv4UeD5ElFAbHNbmy2O8lOtEoSTRjIsfSDzwWZ0HLuBuxBeUecAq2OM93KxXtN
            twV1vvdv+49TH0SWFZoSSWc+95E0yxqjOhJu+SNxN7E8kBaeaYlPXaKSEA9yn/b6
            NhrEPdbtd2HwxfbsJPZAn1812/FEM+Wjr49A6Vd9CJvK+zxqJeOJoLMrtTK23rHa
            GB9tes3/z8O46PkeEnAs3BVBj/mrss2VX/b6Dg7vK/NfZLJZ37+OzoHkgOanIsLj
            0maW21EC4wiA44EPu7UIlBIE4If0bp2sdYXTAkxk2rMRu1++7/w1BchN4iAYyXUR
            NGcpNC9nY/l28BQHA0vj6kRhqR6xGNpvaSoU+0GVL3cyEwOc2IzOYfHozJpZOKVY
            z02WhoDclkbhtbfXysKf5KiMnU2QsfdMOAUS7A/LjZloOrQUvvu3wAy+5TIU9k8o
            1RefyOEY9g17yKf+Lt7DnTMjvo4L+7tjI54Rw5LW/tm+ZRg98Qr9WZAuPFVUMVmU
            PBK/Hh0sOzg8IYNx6AIjDW0wK7T9yDCyfOlvXO6OBwAQakq8y/GrPlok0EF3dFOC
            GO0Ml980B2Ny4jtOHyhcQfZZhcXmLowVvbIV3/JTPk7R63HVowzCzg5n5RBpllPS
            XgH5MjALZIyD/C7NzCpIOYQgrdF4Rr/GgdIwh+WpGTY6ypxhwE8v+FzjvA43vOy+
            gxgWuKNzwKTfm877r+6dgOOzRnMyI6i4V5DFUbJ778hYrSP/UN9kjXOo2P7pUjU=
            =reZN
            -----END PGP MESSAGE-----
          fp: F2D69C1B0CC762DD3814C50C58C374DB3C89C7DE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: cis-provider-secret
    namespace: btp-co-demo
type: Opaque
stringData:
    data: ENC[AES256_GCM,data:tON4HcF1XT47aSR49L9q6Nt9Tbg/mLAfbeHVjoScDhQyOsLMOHbhZOUTpmrMpzHoU3WLq6R2kSvPQgqcvN4fwK5toaEnBVE3Vb/Vd/uyT60+7KHKusGHll36uIIIH03Edw5u0oXVVE88OtZjchBjzP0/vrK7LPYJrsI9RNykmpR17V+OGQLO+AHzIjWQJtrI0a1I7LLOVl209uOLk4JPPAKqtL/ykZvdwLOh8C9UELijhKRiAV747sRWTrAQj/0+1M5w6VF2VuJk624lIZ/chsDKjK/zViLDxmivuLATDzJIR/PErsdEfRhUqXM+MWqtVOWoH9w27/cj5nDAyQrFXp/GHuD7PyLfTz+noDrG7PVAGE9qf6CHHuGPB4bRczC942xHx4LhK0kbXiDqNVBYIZFi4ecZCiIxUUrJ/dHTVxFBKscjXfQ08Lf8t+wYo31fs3Hes0svDkr723LEwQfhphxqdUDshAE16X7cL0Zlnzpop1W+D3ksH9g4Q+fWFmeosZsZnEsvhtOf2bbYqYn2R+1TM3vqQsTrfR7/r/xDmEciAaF1+aAXp8RdF4fOxjeMDzsGFxiYcTmHl3lsLaS6THZvtm7ltrzQ72ejpvXh+aK2nXtSI0NbSJOty+y8kHRIjEZDKPoRwGPCaKrojhOX8XJ1rffgN/Rz/llJmlj1Kye5fu4spT4uYov/MHoHDAq5KC0xR482ER//hk7sCNgrjJKAKBPz84XGixIk81gb4KLwKlaMXgW1cnqBtnd3d4XtXQeIDXa43dA4tUahPbOG5ZuNwrrDvXi+J8uGCImJtoLSpPEsYPRrXYn0Bimgfp/k24LH5HbI/0+bTE6rE5LVObCcVW6PrDtNjF4x6/yOzmVT3HzbOWTS7keb7/kciKJubH/byWJ47ndayLf9f0/qXysB3kYdT48w50lzE9Dy7o6w9cCZq09w8V0k2tY97frO8npIy3bQF8IWeYGf7MGkKe75DNWjj+O8BiCSm4rmGfJKu6jvldCD8hLOGY7o2nhQNgHxHsbqSrxFLdUnuNB1BtJb8gIpDV68Djouvsd85Ph9QLLOVTg3vu6EDlcFlPqrvFcXqhJcp6G/PMZkCgOnfBzqegudVDCWMufozD3Qk3Uh2MYPytMw8xhus8U7bTvfNaQXG5TU+g7Trx4y5u3B3q2bDQo0o2LiMixFNwykZxfp3TOH5cVBOZkz9qyWxbdoEq9RSUVD0Lx49zEL6R9Lca2ULbf3/Oer4ZgAzyGANxbiwJ5QMExd2r7NomdLTrU7+CpkJJ6y99FYePT44JfPPu6tNm4YHfhXusGcoIlPVqnJy+CdGPqhkZTq7m3UQIhoxafBCwIWbvXhsw9+GKBFYzExf/KugLCddzrl5H/xQ9/iPNx8uIQZRqXka7mvweQBL5JowhPPQN8Peh7epQdsjL4UBEeByFhhRo62VkABtB/4m0ZsTCHuH6esUFn1vKbXGKcm2uSHFBh7sJTzGSL/avPdMRKrQ3vM2VWKcQLpBTyDdZEzYNlPRlSGVrl1HSeItt86Kq39U4tnlim1A6UpW/YJQ5bBQcpuLxnfliukq5vwlC7rdRpYznQJLPoKjT8+2x+rtItYqNzKTEsLGgTQrk9853dlzKnjgm5+3SqZbsaPJtz7VUnU0Ym1wHPqPxl+6qTCSUE3iBbOeqVV7WTp7yT2O2lPts6XLIX6uPA+Twl2twNV9GldinaJuQMII9jLR3EfmXvzG4gn/X7hYOtPLln8RplWZYO5YCGdTyULRmUqrCTOWuC2m8tLXCfye49a1X8/omZ0f6AOY1eRX3zFwh5nOW2+vvykLDfIV5CcVCda+ZtJDcqXfLsh/zj8W5KGvYd3uz6x/HwaeGc/umIUwRc3Q2HhpAFJzqm/jv+I6iyhGODUtCkKL1FqnwUk4pPVcFxuahH5OZmMtPgh0g8A8hqnt3xv3veDyRvmzrYbW33gb+iaMr20XAfFeMKalSXQ7xJ3xRLQK4dku72/I8X9vYFWdaLejXq6jTKZ29tS1cNhro/VC2jt9jNflY4+ZClvznzq3tX3g6jcvHKQcJYnIdOwxYRL0lnute5WSNzPWX6Iulkpj9mFTB6jT5GJqsI9qLHPKzhcfEvJPUe0DVsfPKajs4L9l4CcLQwe2Vh03h9mcBR1MbEp4xyCAsFsVg88HB3j+RO9RBdx2LwO+QQNV1ZQwRW7RTf+q2/ezQHnVpzb/DtkIx2+FeqlO2mgNP6h7Jg9bR+24iFKFkaNOAr9dBHVMX5Ospkpsm4NbU5ORi87ORX9hVQc/vpq9T/lj4Daj/DZ+/fd/I3we8GVkdNCBQ2bgmSisCsxaAmznfF9B/eF7EspM6RU9Fe1NlQK/ftObhjwK7IlU9BTuJIsACituMJiujXtYwNeacuSrruTxpDrJQHL7kZPyLUN8GX6L77eLCJWUz8I4lAzmDd9zuk6oT2w5IoNWgS+822zbWKFJOZxWEOXt9/9ef8W6oKWwepxaD4b0EXYq28f6EPPw420Rgg304bpWs4PnRC2rYB/1RH3gvwIZau/XFR8O0+/n60i50fYreJE4ApzfWSDbbW+QLpunlGOVAwbR9G3DldMGNbXzIT83kdUECMQUdWJTvuC9hd+7mNWczj4nDZ4MA98Xo2deYa/p86QDr+/GP7qpsFL5IXR/xbhjkm6EioalygtiQXQ1AK36lze9Ovt2QMaljx0uZeHXy7xnn1GJ4qwVpSV5zzYhDKRYLcUV9nxkuvIuE0tShNgYpHhcYEK8tWHToloXzEMwExspLwyHUxz3IiY/QAY9ytnbxkwAP06XqnVOT5NEOys9E1hIvzl1IrYfOMqLbO6P7NZPcHGaVgoO3OAixVhdpIfReid6imjYDDBjms7+r7SH0Rs+DE+Bw4eqpQSd5aHlnOj8ThuoZZ2teFRskEvG6K3Q+t+/5sOVynNP8zBkUob/fU447zljg4jI0qeHji1xOnO9hvgC4O+UkBtyIjrhuHEnSd8Zt1wRjq1TXXCODVl63lsopvI20RvVgucFwLqHklL3Q2vqRkzw/+5eohDe4HqOIDewehqdhstz51iNyeNmrGLBJdI14w/9gpOfkjrNMJsq6m2wtQ4hEkBh3w6XxUr2P87f3m1VuTZcyVRMu7981LdCy7yOkkdyZTosuZW7DJQw5shCyBox5nE2xs8Pdo1KODJlG2MF/Pb,iv:PPwG865HBjagQlDHPoJwpFQriKQslb+7aafOSFvhNhk=,tag:xA0Gs65NTQhrYaQZeh2mUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-25T19:13:44Z"
    mac: ENC[AES256_GCM,data:oqQt+tRI6dYL5K5ei9FWlnX0FPlsHyEmTDqbteBnzwu3p71KAV+ZZDAqs4HJ3uVcVuliwlq+z3xG/JfNKPZIFMW4qRZA98jxZGNyu1y/5iKFfCsIrLzoW8WBn9Y0YItxufnYbx9DeK3tSyjrrrInIx1SKcEyj9J+uwps8IJSCxE=,iv:by+4SUSaqFcIIljcNokiWYBA3ceIwSe5MGqpLml1f+s=,tag:RtSnRl0JuTbzMbsF/3sZww==,type:str]
    pgp:
        - created_at: "2023-03-25T19:13:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+09R1QdBDPoAQ/9GXrccmbQdcpTjp9s9oycodg2yE1Ok+JpHYhUUZAf2w1h
            kBXv4UeD5ElFAbHNbmy2O8lOtEoSTRjIsfSDzwWZ0HLuBuxBeUecAq2OM93KxXtN
            twV1vvdv+49TH0SWFZoSSWc+95E0yxqjOhJu+SNxN7E8kBaeaYlPXaKSEA9yn/b6
            NhrEPdbtd2HwxfbsJPZAn1812/FEM+Wjr49A6Vd9CJvK+zxqJeOJoLMrtTK23rHa
            GB9tes3/z8O46PkeEnAs3BVBj/mrss2VX/b6Dg7vK/NfZLJZ37+OzoHkgOanIsLj
            0maW21EC4wiA44EPu7UIlBIE4If0bp2sdYXTAkxk2rMRu1++7/w1BchN4iAYyXUR
            NGcpNC9nY/l28BQHA0vj6kRhqR6xGNpvaSoU+0GVL3cyEwOc2IzOYfHozJpZOKVY
            z02WhoDclkbhtbfXysKf5KiMnU2QsfdMOAUS7A/LjZloOrQUvvu3wAy+5TIU9k8o
            1RefyOEY9g17yKf+Lt7DnTMjvo4L+7tjI54Rw5LW/tm+ZRg98Qr9WZAuPFVUMVmU
            PBK/Hh0sOzg8IYNx6AIjDW0wK7T9yDCyfOlvXO6OBwAQakq8y/GrPlok0EF3dFOC
            GO0Ml980B2Ny4jtOHyhcQfZZhcXmLowVvbIV3/JTPk7R63HVowzCzg5n5RBpllPS
            XgH5MjALZIyD/C7NzCpIOYQgrdF4Rr/GgdIwh+WpGTY6ypxhwE8v+FzjvA43vOy+
            gxgWuKNzwKTfm877r+6dgOOzRnMyI6i4V5DFUbJ778hYrSP/UN9kjXOo2P7pUjU=
            =reZN
            -----END PGP MESSAGE-----
          fp: F2D69C1B0CC762DD3814C50C58C374DB3C89C7DE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
